"""Embedded configuration and control web server for BangumiKomga.

This module intentionally uses only the Python standard library so the Docker
image remains small and the original scraper can still be used unchanged.
"""
from __future__ import annotations

import ast
import hashlib
import json
import os
import secrets
import sqlite3
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parent
CONFIG_DIR = ROOT / "config"
WEB_DIR = ROOT / "web"
WEB_STATE = CONFIG_DIR / "web_config.json"
DATA_DIR = Path(os.getenv("BANGUMI_KOMGA_DATA_DIR", str(ROOT / "data")))
# Credentials intentionally live beside the generated config so the existing
# /app/config volume is the single persistence boundary.
AUTH_STATE = CONFIG_DIR / "web_auth.json"
CONFIG_FILE = CONFIG_DIR / "config.py"
PORT = int(os.getenv("BANGUMI_KOMGA_WEB_PORT", "15600"))

DEFAULTS = {
    "BANGUMI_ACCESS_TOKEN": "",
    "KOMGA_BASE_URL": "",
    "KOMGA_EMAIL": "",
    "KOMGA_EMAIL_PASSWORD": "",
    "KOMGA_API_KEY": "",
    "KOMGA_LIBRARY_LIST": [],
    "KOMGA_COLLECTION_LIST": [],
    "USE_BANGUMI_ARCHIVE": False,
    "ARCHIVE_FILES_DIR": "./archivedata/",
    "ARCHIVE_UPDATE_INTERVAL": 168,
    "BANGUMI_KOMGA_SERVICE_TYPE": "poll",
    "BANGUMI_KOMGA_SERVICE_POLL_INTERVAL": 20,
    "BANGUMI_KOMGA_SERVICE_POLL_REFRESH_ALL_METADATA_INTERVAL": 10000,
    "USE_BANGUMI_THUMBNAIL": False,
    "USE_BANGUMI_THUMBNAIL_FOR_BOOK": False,
    "SORT_TITLE": False,
    "FUZZ_SCORE_THRESHOLD": 80,
    "RECHECK_FAILED_SERIES": False,
    "RECHECK_FAILED_BOOKS": False,
    "CREATE_FAILED_COLLECTION": False,
    "ADD_LOCAL_VERSION": False,
    "NOTIF_TYPE_ENABLE": [],
    "NOTIF_GOTIFY_ENDPOINT": "http://IP:PORT",
    "NOTIF_GOTIFY_TOKEN": "TOKEN",
    "NOTIF_GOTIFY_PRIORITY": 1,
    "NOTIF_GOTIFY_TIMEOUT": 10,
    "NOTIF_WEBHOOK_ENDPOINT": "http://IP:PORT",
    "NOTIF_WEBHOOK_METHOD": "POST",
    "NOTIF_WEBHOOK_HEADER": '{"Content-Type": "application/json"}',
    "NOTIF_WEBHOOK_TIMEOUT": 10,
    "NOTIF_HEALTHCHECKS_ENDPOINT": "http://IP:PORT",
    "NOTIF_HEALTHCHECKS_TIMEOUT": 10,
}

STATE_LOCK = threading.RLock()
REFRESH_LOCK = threading.Lock()
REFRESH_STATE = {"running": False, "last_result": None, "last_error": None}
SESSIONS = set()


def _password_hash(password):
    return hashlib.sha256(password.encode("utf-8")).hexdigest()


def _read_auth():
    with STATE_LOCK:
        if AUTH_STATE.exists():
            try:
                data = json.loads(AUTH_STATE.read_text(encoding="utf-8"))
                if data.get("username") and data.get("password_hash"):
                    return data
            except (OSError, ValueError):
                pass
        return {"username": "admin", "password_hash": _password_hash("password")}


def _save_auth(username, password):
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    data = {"username": username, "password_hash": _password_hash(password)}
    AUTH_STATE.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return {"username": username}


def _read_state() -> dict:
    with STATE_LOCK:
        if WEB_STATE.exists():
            try:
                data = json.loads(WEB_STATE.read_text(encoding="utf-8"))
                return {**DEFAULTS, **data}
            except (OSError, ValueError):
                pass
        return dict(DEFAULTS)


def _python_value(value):
    if isinstance(value, bool):
        return "True" if value else "False"
    if value is None:
        return "None"
    return repr(value)


def _write_config(data: dict):
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by BangumiKomga Web UI. Edit via the Web UI when possible.", ""]
    for key, default in DEFAULTS.items():
        lines.append(f"{key} = {_python_value(data.get(key, default))}")
    CONFIG_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def save_state(data: dict) -> dict:
    merged = {**DEFAULTS, **data}
    # Normalize card values and keep the config file safe to import.
    libraries = []
    for item in merged.get("KOMGA_LIBRARY_LIST", []) or []:
        if not item.get("LIBRARY"):
            continue
        libraries.append({
            "LIBRARY": str(item["LIBRARY"]),
            "IS_NOVEL_ONLY": bool(item.get("IS_NOVEL_ONLY", False)),
            "REQUIRED_FIELDS": list(item.get("REQUIRED_FIELDS", []) or []),
        })
    merged["KOMGA_LIBRARY_LIST"] = libraries
    merged["KOMGA_COLLECTION_LIST"] = [
        {"COLLECTION": str(x["COLLECTION"]), "IS_NOVEL_ONLY": bool(x.get("IS_NOVEL_ONLY", False)),
         "REQUIRED_FIELDS": list(x.get("REQUIRED_FIELDS", []) or [])}
        for x in (merged.get("KOMGA_COLLECTION_LIST", []) or []) if x.get("COLLECTION")
    ]
    with STATE_LOCK:
        WEB_STATE.write_text(json.dumps(merged, ensure_ascii=False, indent=2), encoding="utf-8")
        _write_config(merged)
    return merged


def _load_komga():
    state = _read_state()
    if not state.get("KOMGA_BASE_URL"):
        raise ValueError("请先保存 Komga 地址")
    if not state.get("KOMGA_API_KEY") and (not state.get("KOMGA_EMAIL") or not state.get("KOMGA_EMAIL_PASSWORD")):
        raise ValueError("请填写 Komga 账号密码或 API 密钥")
    from api.komga_api import KomgaApi
    return KomgaApi(state["KOMGA_BASE_URL"], state.get("KOMGA_EMAIL", ""), state.get("KOMGA_EMAIL_PASSWORD", ""), state.get("KOMGA_API_KEY") or None)


def _start_refresh(full=False):
    if not REFRESH_LOCK.acquire(blocking=False):
        return False
    REFRESH_STATE.update({"running": True, "last_error": None})

    def worker():
        try:
            # Import only after config.py exists and in the worker so the web UI
            # remains available even on a fresh installation.
            from core.refresh_metadata import refresh_metadata, refresh_partial_metadata
            (refresh_metadata if full else refresh_partial_metadata)()
            REFRESH_STATE["last_result"] = "full" if full else "incremental"
        except Exception as exc:  # pragma: no cover - surfaced through API
            REFRESH_STATE["last_error"] = str(exc)
        finally:
            REFRESH_STATE["running"] = False
            REFRESH_LOCK.release()

    threading.Thread(target=worker, name="WebRefresh", daemon=True).start()
    return True


def _read_scrape_records(limit=100, offset=0):
    db_file = ROOT / "recordsRefreshed.db"
    if not db_file.exists():
        return []
    try:
        configured_ids = [
            str(item.get("LIBRARY"))
            for item in (_read_state().get("KOMGA_LIBRARY_LIST") or [])
            if item.get("LIBRARY")
        ]
        if not configured_ids:
            return []
        with sqlite3.connect(db_file) as conn:
            placeholders = ",".join("?" for _ in configured_ids)
            rows = conn.execute(
                """SELECT id,item_type,item_title,library_id,library_name,
                   metadata_fields,status,recorded_at
                   FROM scrape_records WHERE library_id IN (""" + placeholders + """)
                   ORDER BY id DESC LIMIT ? OFFSET ?""",
                (*configured_ids, limit, offset),
            ).fetchall()
        return [
            {
                "id": row[0], "item_type": row[1], "item_title": row[2],
                "library_id": row[3], "library_name": row[4],
                "metadata_fields": [field for field in row[5].split(",") if field],
                "status": row[6], "recorded_at": row[7],
            }
            for row in rows
        ]
    except (OSError, sqlite3.Error):
        return []


class Handler(BaseHTTPRequestHandler):
    server_version = "BangumiKomgaWeb/1.0"

    def log_message(self, *_args):
        return

    def _json(self, status, payload):
        raw = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def _body(self):
        size = int(self.headers.get("Content-Length", "0"))
        return json.loads(self.rfile.read(size) or b"{}")

    def _session_token(self):
        cookies = self.headers.get("Cookie", "").split(";")
        for cookie in cookies:
            key, _, value = cookie.strip().partition("=")
            if key == "bk_session":
                return value
        return None

    def _authorized(self):
        return self._session_token() in SESSIONS

    def _require_auth(self):
        if self._authorized():
            return True
        self._json(401, {"error": "请先登录"})
        return False

    def do_GET(self):  # noqa: N802
        path = urlparse(self.path).path
        if path == "/api/auth/session":
            self._json(200, {"authenticated": self._authorized(), "username": _read_auth()["username"]})
        elif path.startswith("/api/") and not self._authorized():
            self._json(401, {"error": "请先登录"})
        elif path == "/api/config":
            self._json(200, _read_state())
        elif path == "/api/status":
            self._json(200, REFRESH_STATE)
        elif path == "/api/scrape-records":
            query = dict(item.split("=", 1) for item in urlparse(self.path).query.split("&") if "=" in item)
            try:
                limit = max(20, min(int(query.get("limit", 100)), 200))
                offset = max(0, int(query.get("offset", 0)))
            except ValueError:
                limit, offset = 100, 0
            self._json(200, {"items": _read_scrape_records(limit, offset)})
        elif path == "/api/komga/libraries":
            try:
                self._json(200, {"items": _load_komga().list_libraries()})
            except Exception as exc:
                self._json(400, {"error": str(exc)})
        elif path == "/api/komga/collections" and self._require_auth():
            try:
                self._json(200, {"items": _load_komga().list_collections()})
            except Exception as exc:
                self._json(400, {"error": str(exc)})
        else:
            self._serve_static(path)

    def do_POST(self):  # noqa: N802
        path = urlparse(self.path).path
        try:
            if path == "/api/auth/login":
                body = self._body()
                auth = _read_auth()
                if body.get("username") != auth["username"] or _password_hash(body.get("password", "")) != auth["password_hash"]:
                    self._json(401, {"error": "账号或密码错误"})
                    return
                token = secrets.token_urlsafe(32)
                SESSIONS.add(token)
                raw = json.dumps({"authenticated": True, "username": auth["username"]}, ensure_ascii=False).encode("utf-8")
                self.send_response(200)
                self.send_header("Content-Type", "application/json; charset=utf-8")
                self.send_header("Set-Cookie", f"bk_session={token}; Path=/; HttpOnly; SameSite=Strict")
                self.send_header("Content-Length", str(len(raw)))
                self.end_headers()
                self.wfile.write(raw)
            elif path == "/api/auth/logout":
                token = self._session_token()
                if token:
                    SESSIONS.discard(token)
                self._json(200, {"authenticated": False})
            elif path == "/api/auth/credentials" and self._require_auth():
                body = self._body()
                username = str(body.get("username", "")).strip()
                password = str(body.get("password", ""))
                if not username or not password:
                    self._json(400, {"error": "账号和密码不能为空"})
                    return
                self._json(200, _save_auth(username, password))
            elif path == "/api/config" and self._require_auth():
                self._json(200, save_state(self._body()))
            elif path == "/api/refresh" and self._require_auth():
                body = self._body()
                if _start_refresh(bool(body.get("full", False))):
                    self._json(202, {"started": True})
                else:
                    self._json(409, {"started": False, "error": "已有刷新任务正在运行"})
            else:
                self._json(404, {"error": "not found"})
        except Exception as exc:
            self._json(400, {"error": str(exc)})

    def _serve_static(self, path):
        relative = "index.html" if path in ("", "/") else path.lstrip("/")
        target = (WEB_DIR / relative).resolve()
        if WEB_DIR not in target.parents and target != WEB_DIR:
            self._json(403, {"error": "forbidden"})
            return
        if not target.exists() or not target.is_file():
            self._json(404, {"error": "not found"})
            return
        content_type = "text/html; charset=utf-8" if target.suffix == ".html" else "text/plain; charset=utf-8"
        if target.suffix == ".js":
            content_type = "application/javascript; charset=utf-8"
        elif target.suffix == ".css":
            content_type = "text/css; charset=utf-8"
        raw = target.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)


def start_web_server(port=PORT):
    server = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    threading.Thread(target=server.serve_forever, name="WebServer", daemon=True).start()
    return server


if __name__ == "__main__":
    start_web_server().serve_forever()
