"""Embedded configuration and control web server for BangumiKomga.

This module intentionally uses only the Python standard library so the Docker
image remains small and the original scraper can still be used unchanged.
"""
from __future__ import annotations

import ast
import json
import os
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parent
CONFIG_DIR = ROOT / "config"
WEB_DIR = ROOT / "web"
WEB_STATE = CONFIG_DIR / "web_config.json"
CONFIG_FILE = CONFIG_DIR / "config.py"
PORT = int(os.getenv("BANGUMI_KOMGA_WEB_PORT", "15600"))

DEFAULTS = {
    "BANGUMI_ACCESS_TOKEN": "",
    "KOMGA_BASE_URL": "",
    "KOMGA_EMAIL": "",
    "KOMGA_EMAIL_PASSWORD": "",
    "KOMGA_LIBRARY_LIST": [],
    "KOMGA_COLLECTION_LIST": [],
    "USE_BANGUMI_ARCHIVE": False,
    "ARCHIVE_FILES_DIR": "./archivedata/",
    "ARCHIVE_UPDATE_INTERVAL": 168,
    "BANGUMI_KOMGA_SERVICE_TYPE": "poll",
    "BANGUMI_KOMGA_SERVICE_POLL_INTERVAL": 20,
    "BANGUMI_KOMGA_SERVICE_POLL_REFRESH_ALL_METADATA_INTERVAL": 10000,
    "USE_BANGUMI_THUMBNAIL": False,
    "USE_BANGUMI_THUMBNAIL_FOR_BOOK": False,
    "SORT_TITLE": False,
    "FUZZ_SCORE_THRESHOLD": 80,
    "RECHECK_FAILED_SERIES": False,
    "RECHECK_FAILED_BOOKS": False,
    "CREATE_FAILED_COLLECTION": False,
    "ADD_LOCAL_VERSION": False,
    "NOTIF_TYPE_ENABLE": [],
    "NOTIF_GOTIFY_ENDPOINT": "http://IP:PORT",
    "NOTIF_GOTIFY_TOKEN": "TOKEN",
    "NOTIF_GOTIFY_PRIORITY": 1,
    "NOTIF_GOTIFY_TIMEOUT": 10,
    "NOTIF_WEBHOOK_ENDPOINT": "http://IP:PORT",
    "NOTIF_WEBHOOK_METHOD": "POST",
    "NOTIF_WEBHOOK_HEADER": '{"Content-Type": "application/json"}',
    "NOTIF_WEBHOOK_TIMEOUT": 10,
    "NOTIF_HEALTHCHECKS_ENDPOINT": "http://IP:PORT",
    "NOTIF_HEALTHCHECKS_TIMEOUT": 10,
}

STATE_LOCK = threading.RLock()
REFRESH_LOCK = threading.Lock()
REFRESH_STATE = {"running": False, "last_result": None, "last_error": None}


def _read_state() -> dict:
    with STATE_LOCK:
        if WEB_STATE.exists():
            try:
                data = json.loads(WEB_STATE.read_text(encoding="utf-8"))
                return {**DEFAULTS, **data}
            except (OSError, ValueError):
                pass
        return dict(DEFAULTS)


def _python_value(value):
    if isinstance(value, bool):
        return "True" if value else "False"
    if value is None:
        return "None"
    return repr(value)


def _write_config(data: dict):
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by BangumiKomga Web UI. Edit via the Web UI when possible.", ""]
    for key, default in DEFAULTS.items():
        lines.append(f"{key} = {_python_value(data.get(key, default))}")
    CONFIG_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def save_state(data: dict) -> dict:
    merged = {**DEFAULTS, **data}
    # Normalize card values and keep the config file safe to import.
    libraries = []
    for item in merged.get("KOMGA_LIBRARY_LIST", []) or []:
        if not item.get("LIBRARY"):
            continue
        libraries.append({
            "LIBRARY": str(item["LIBRARY"]),
            "IS_NOVEL_ONLY": bool(item.get("IS_NOVEL_ONLY", False)),
            "REQUIRED_FIELDS": list(item.get("REQUIRED_FIELDS", []) or []),
        })
    merged["KOMGA_LIBRARY_LIST"] = libraries
    merged["KOMGA_COLLECTION_LIST"] = [
        {"COLLECTION": str(x["COLLECTION"]), "IS_NOVEL_ONLY": bool(x.get("IS_NOVEL_ONLY", False)),
         "REQUIRED_FIELDS": list(x.get("REQUIRED_FIELDS", []) or [])}
        for x in (merged.get("KOMGA_COLLECTION_LIST", []) or []) if x.get("COLLECTION")
    ]
    with STATE_LOCK:
        WEB_STATE.write_text(json.dumps(merged, ensure_ascii=False, indent=2), encoding="utf-8")
        _write_config(merged)
    return merged


def _load_komga():
    state = _read_state()
    if not state.get("KOMGA_BASE_URL") or not state.get("KOMGA_EMAIL"):
        raise ValueError("请先保存 Komga 地址、邮箱和密码")
    from api.komga_api import KomgaApi
    return KomgaApi(state["KOMGA_BASE_URL"], state["KOMGA_EMAIL"], state["KOMGA_EMAIL_PASSWORD"])


def _start_refresh(full=False):
    if not REFRESH_LOCK.acquire(blocking=False):
        return False
    REFRESH_STATE.update({"running": True, "last_error": None})

    def worker():
        try:
            # Import only after config.py exists and in the worker so the web UI
            # remains available even on a fresh installation.
            from core.refresh_metadata import refresh_metadata, refresh_partial_metadata
            (refresh_metadata if full else refresh_partial_metadata)()
            REFRESH_STATE["last_result"] = "full" if full else "incremental"
        except Exception as exc:  # pragma: no cover - surfaced through API
            REFRESH_STATE["last_error"] = str(exc)
        finally:
            REFRESH_STATE["running"] = False
            REFRESH_LOCK.release()

    threading.Thread(target=worker, name="WebRefresh", daemon=True).start()
    return True


class Handler(BaseHTTPRequestHandler):
    server_version = "BangumiKomgaWeb/1.0"

    def log_message(self, *_args):
        return

    def _json(self, status, payload):
        raw = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def _body(self):
        size = int(self.headers.get("Content-Length", "0"))
        return json.loads(self.rfile.read(size) or b"{}")

    def do_GET(self):  # noqa: N802
        path = urlparse(self.path).path
        if path == "/api/config":
            self._json(200, _read_state())
        elif path == "/api/status":
            self._json(200, REFRESH_STATE)
        elif path == "/api/komga/libraries":
            try:
                self._json(200, {"items": _load_komga().list_libraries()})
            except Exception as exc:
                self._json(400, {"error": str(exc)})
        elif path == "/api/komga/collections":
            try:
                self._json(200, {"items": _load_komga().list_collections()})
            except Exception as exc:
                self._json(400, {"error": str(exc)})
        else:
            self._serve_static(path)

    def do_POST(self):  # noqa: N802
        path = urlparse(self.path).path
        try:
            if path == "/api/config":
                self._json(200, save_state(self._body()))
            elif path == "/api/refresh":
                body = self._body()
                if _start_refresh(bool(body.get("full", False))):
                    self._json(202, {"started": True})
                else:
                    self._json(409, {"started": False, "error": "已有刷新任务正在运行"})
            else:
                self._json(404, {"error": "not found"})
        except Exception as exc:
            self._json(400, {"error": str(exc)})

    def _serve_static(self, path):
        relative = "index.html" if path in ("", "/") else path.lstrip("/")
        target = (WEB_DIR / relative).resolve()
        if WEB_DIR not in target.parents and target != WEB_DIR:
            self._json(403, {"error": "forbidden"})
            return
        if not target.exists() or not target.is_file():
            self._json(404, {"error": "not found"})
            return
        content_type = "text/html; charset=utf-8" if target.suffix == ".html" else "text/plain; charset=utf-8"
        if target.suffix == ".js":
            content_type = "application/javascript; charset=utf-8"
        elif target.suffix == ".css":
            content_type = "text/css; charset=utf-8"
        raw = target.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)


def start_web_server(port=PORT):
    server = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    threading.Thread(target=server.serve_forever, name="WebServer", daemon=True).start()
    return server


if __name__ == "__main__":
    start_web_server().serve_forever()
