document.addEventListener('DOMContentLoaded', async () => {
  const $ = id => document.getElementById(id); const state = {config:{},libraries:[]};
  const show=(text,error=false)=>{const e=$('message');e.hidden=!text;e.textContent=text||'';e.className='message'+(error?' error':'')};
  async function api(path,opt={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});const d=await r.json();if(!r.ok)throw new Error(d.error||`请求失败 ${r.status}`);return d}
  function empty(){ $('empty').style.display=$('cards').children.length?'none':'block' }
  function addCard(v={}){const card=$('card-template').content.firstElementChild.cloneNode(true),sel=card.querySelector('.library');state.libraries.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=`${x.name} (${x.id})`;sel.appendChild(o)});sel.value=v.LIBRARY||'';card.querySelector('.novel-check').checked=!!v.IS_NOVEL_ONLY;card.querySelectorAll('fieldset input').forEach(x=>x.checked=(v.REQUIRED_FIELDS||[]).includes(x.value));card.querySelector('.danger').onclick=()=>{card.remove();empty()};$('cards').appendChild(card);empty()}
  function collect(){return {...state.config,KOMGA_BASE_URL:$('base').value.trim(),KOMGA_EMAIL:$('email').value.trim(),KOMGA_EMAIL_PASSWORD:$('password').value,KOMGA_LIBRARY_LIST:[...$('cards').children].map(c=>({LIBRARY:c.querySelector('.library').value,IS_NOVEL_ONLY:c.querySelector('.novel-check').checked,REQUIRED_FIELDS:[...c.querySelectorAll('fieldset input:checked')].map(x=>x.value)})).filter(x=>x.LIBRARY),KOMGA_COLLECTION_LIST:[],BANGUMI_KOMGA_SERVICE_TYPE:$('service').value}}
  async function loadLibraries(){try{const d=await api('/api/komga/libraries');state.libraries=d.items||[];const old=collect().KOMGA_LIBRARY_LIST;$('cards').innerHTML='';old.forEach(addCard);show(`已读取 ${state.libraries.length} 个媒体库`)}catch(e){show(e.message,true)}}
  $('add-card').onclick=()=>addCard();$('load-libraries').onclick=loadLibraries;$('save').onclick=async()=>{try{state.config=await api('/api/config',{method:'POST',body:JSON.stringify(collect())});show('设置已保存。')}catch(e){show(e.message,true)}};
  async function refresh(full){try{await api('/api/refresh',{method:'POST',body:JSON.stringify({full})});show(full?'全量刮削已开始':'增量刮削已开始')}catch(e){show(e.message,true)}} $('incremental').onclick=()=>refresh(false);$('full').onclick=()=>refresh(true);
  async function poll(){try{const s=await api('/api/status');$('status').textContent=s.running?'正在刮削':'服务在线';$('status').className='status live';if(s.last_result)$('last-run').textContent=`最近完成：${s.last_result==='full'?'全量':'增量'}`;if(s.last_error)show(s.last_error,true)}catch(e){$('status').textContent='未连接'}setTimeout(poll,3000)}
  try{state.config=await api('/api/config');$('base').value=state.config.KOMGA_BASE_URL||'';$('email').value=state.config.KOMGA_EMAIL||'';$('password').value=state.config.KOMGA_EMAIL_PASSWORD||'';$('service').value=state.config.BANGUMI_KOMGA_SERVICE_TYPE||'poll';(state.config.KOMGA_LIBRARY_LIST||[]).forEach(addCard)}catch(e){show(e.message,true)}poll();
});
